# Generated by Django 5.1.4 on 2026-05-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escalationlog',
            unique_together={('ticket', 'level')},
        ),
    ]
